### ISSUE TITLE
Reintegrate old room generation

### ISSUE THREAD

**Issue by nightblade9** [nightblade9/furusiya#25]
Randomly decide: forest or dungeon or cave (for now).

[Old code](https://github.com/nightblade9/furusiya/blob/298b547db3cae54bcd55bda2269dfadea196a39c/furusiya/main.py)

- [x] Dungeons
- [x] DRY the common code

NB: `make_dungeon` and `make_cave` methods

**Comment by NegativeScript** [comment]
How about [everything!](https://github.com/nightblade9/furusiya/commit/caf529f3e0af76fefbf236949bac09bf81f164ae)
I guess caves can be delayed... You know, for now.

**Comment by nightblade9** [comment]
@NegativeScript switching is not necessary or useful; my vision is that the final game will be something like:

- Five floors of forest
- Five floors of caves
- Five floors of dungeons
- Five floors I haven't figured out yet

**Comment by NegativeScript** [comment]
I see. But it's already in, so might as well leave it 'till we're actually doing floors.

**Comment by NegativeScript** [comment]
>Fix: dungeons have virtually no monsters/items. Why?

Perhaps because of this?
https://github.com/nightblade9/furusiya/blob/7eb1e2be78ce401cec359e2f0c66d55c6910f54b/furusiya/model/maps/generators/dungeon_generator.py#L173-L184

Items which would've been on non-walkable tiles are skipped, no questions asked.This is also an issue in the forest generator, but there are many more empty tiles in a forest than in a dungeon.
